### ISSUE TITLE
modify guide

### ISSUE THREAD

**Issue by alexgithub56** [having11/NeoPixel-Emulator#1]
Hi, if I would like to build 64x64 RGB matrix emulator. Please advice. Thank you.

**Comment by having11** [comment]
By all means, if you would like to help extend this program by building a matrix component then please do!

**Comment by having11** [comment]
I added a new matrix class that allows for the creation of neopixel matrices. It also has the Adafruit GFX class.

**Comment by alexgithub56** [comment]
Sorry, for replying late. Thank you very much.
Regards,
Anurath
