### ISSUE TITLE
Attempted install via Python 3.9 on Windows 10

### ISSUE THREAD

**Issue by TFAstudio** [having11/NeoPixel-Emulator#2]
Hey there Arduino “having11” Guy,

I'm interested in your Emulator.
It's my first time trying Python and I admit I am not much of a programmer.
I managed to install Python 3.9 with PATH support on Windows 10. I also installed Pyglet successfully.
But when I run your neopixel_viewer.py from the command prompt, I get an error...
`AttributeError: module 'pyglet.graphics' has no attribute 'OrderedGroup'`

Have I run into a compatibility issue?
Any tips to get it going would be great.

Thanks 
AE

**Comment by kittentakara** [comment]
Same issue here, any solutions?

**Comment by TFAstudio** [comment]
As you can see, I got no reply. A shame as I was keen to get into it. Uninstalled everything now.

**Comment by kittentakara** [comment]
Yeah sadly, I am just going have find another way of doing it this. Was hoping they would have answered your question :(

**Comment by cabillin** [comment]
I ran into this same issue. I was able to get neopixel_viewer.py running successfully by installing https://pypi.org/project/pyglet/1.5.27/ (based on the fact that the [2.0 release notes](https://github.com/pyglet/pyglet/blob/92bd2241d6d17cf1bcfc2809c02a7446678b1ece/doc/programming_guide/migration.rst) mentioned removing OrderedGroup)

**Comment by having11** [comment]
Yes, installing `1.5.17` does work. I will add a `requirements.txt` file
